import { Theme } from "theme.slint";

export component Divider {
    in property <bool> vertical: false;
    in property <length> inset: 0px;
    in property <length> prop-padding;
    if (!root.vertical): HorizontalLayout {
        width: 100%;
        height: Theme.strokeWidthThin;
        padding-left: prop-padding;
        padding-right: prop-padding;
        x: root.inset;
        Rectangle {
            background: Theme.colorNeutralBackgroundAlpha2;

            width: parent.width - root.inset * 2;
            height: parent.height;
        }
    }

    if (root.vertical): VerticalLayout {
        width: Theme.strokeWidthThin;
        height: 100%;
        padding-top: prop-padding;
        padding-bottom: prop-padding;
        y: root.inset;

        Rectangle {
            background: Theme.colorNeutralBackgroundAlpha2;
            height: parent.height - root.inset * 2;
            width: parent.width;
        }
    }
}
