
import { Theme } from "theme.slint";

export component SelectionIndicator inherits Rectangle {

    in property <bool> is-active: false;

    if (is-active): Rectangle {
        x: 0;
        width: Theme.selection_indicator_width;
        height: Theme.selection_indicator_height;
        background: Theme.accent_2;
        border-radius: Theme.border_radius_xs;
        y: (parent.height - self.height) / 2;

        animate height {
            duration: Theme.fast_animation_time;
            easing: ease-out;
        }
        animate opacity { duration: Theme.slow_animation_time; }
    }
}
