
export global Theme {

    in-out property <bool> is_dark: true;

    out property <color> background: is_dark ? #1c1c1c : #f3f3f3;
    out property <color> surface: is_dark ? #1a1a1a : #ffffff;
    out property <color> layer_background: is_dark ? rgba(255, 255, 255, 0.05) : rgba(0, 0, 0, 0.05);
    out property <color> layer_background2: is_dark ? rgba(255, 255, 255, 0.01) : rgba(0, 0, 0, 0.01);

    out property <color> text_primary: is_dark ? #ffffff : #000000;
    out property <color> text_secondary: is_dark ? #d1d1d1 : #616161;
    out property <color> text_disabled: is_dark ? #858585 : #9e9e9e;

    out property <color> fill_subtle_hover: is_dark ? rgba(255, 255, 255, 0.03) : rgba(0, 0, 0, 0.03);
    out property <color> fill_subtle_secondary: is_dark ? rgba(255, 255, 255, 0.06) : rgba(0, 0, 0, 0.06);
    out property <color> fill_transparent: transparent;

    in-out property <color> accent: #0078d4;
    out property <color> accent_hover: accent.darker(10%);
    out property <color> accent_text: #ffffff;

    out property <color> border: is_dark ? #444444 : #e5e5e5;
    out property <color> control_border: is_dark ? #3d3d3d : #d1d1d1;

    out property <length> spacing_xs: 4px;
    out property <length> spacing_s: 8px;
    out property <length> spacing_m: 12px;
    out property <length> spacing_l: 16px;
    out property <length> border_radius_xs: 2px;
    out property <length> border_radius_s: 4px;
    out property <length> border_radius_m: 8px;

    out property <length> icon_size_s: 12px;
    out property <length> icon_size_m: 16px;
    out property <length> icon_size_l: 20px;

    out property <length> title_bar_height: 32px;
    out property <length> title_control_width: 46px;
    out property <length> selection_indicator_width: 3px;
    out property <length> selection_indicator_height: 15px;

    out property <length> font_size_body: 14px;
    out property <length> font_size_caption: 12px;
    out property <length> font_size_title: 20px;

    out property <color> success: #00cc6a;
    out property <color> offline: is_dark ? #8a8a8a : #616161;
    out property <color> warn: #c48705;
    out property <color> disabled: is_dark ? rgba(255,255,255,0.15) : rgba(0,0,0,0.15);
    out property <color> item_active_background: accent.with_alpha(0.1);

    out property <color> title_control_hover: is_dark ? rgba(255, 255, 255, 0.05) : rgba(0, 0, 0, 0.06);
    out property <color> title_control_pressed: is_dark ? rgba(255, 255, 255, 0.10) : rgba(0, 0, 0, 0.12);
    out property <color> title_close: #e81123;
    out property <color> title_icon: is_dark ? rgba(255, 255, 255, 0.9) : rgba(0, 0, 0, 0.85);
    out property <color> title_icon_active: #ffffff;

    out property <duration> fast_animation_time: 150ms;
    out property <duration> primary_animation_time: 100ms;
    out property <duration> slow_animation_time: 200ms;
}
