import { Theme } from "theme.slint";
import { Button } from "button/index.slint";

export enum ContentDialogMode {
    inline,
    window
}

export component ContentDialogButtonFooter inherits Rectangle {
    in property <length> footer-padding-x: Theme.spacingHorizontalL;
    in property <length> footer-padding-y: Theme.spacingVerticalL;

    in property <bool> is-windowed: true;

    height: 80px;
    border-width: is-windowed ? 0px : 1px;
    border-color: is-windowed ? transparent : Theme.colorNeutralStroke3;
    border-bottom-left-radius: Theme.border_radius_m;
    border-bottom-right-radius: Theme.border_radius_m;
    background: is-windowed ? transparent : Theme.colorNeutralBackground3;

    VerticalLayout {
        alignment: center;
        HorizontalLayout {
            spacing: Theme.spacingHorizontalS;
            alignment: end;

            @children
        }
    }
}

export component ContentDialog inherits Rectangle {
    in property <length> dialog-width: 460px;
    
    in property <bool> has-footer: false;
    in property <bool> is-windowed: false;
    in property <color> footer-background: Theme.colorNeutralBackground1;
    in property <color> footer-border-color: Theme.colorNeutralStroke3;

    width: root.dialog-width;
    
    border-radius: Theme.borderRadiusXLarge;
    border-bottom-right-radius: 0px;
    border-bottom-left-radius: 0px;
    border-width: 1px;
    border-color: Theme.colorNeutralStroke3;
    drop-shadow-blur: is-windowed ? 0px : 20px;
    drop-shadow-color: is-windowed ? transparent : Colors.black.with-alpha(0.28);

    TouchArea { }

    VerticalLayout {
        padding-left: is-windowed ? Theme.spacingHorizontalXL : Theme.spacingHorizontalL;
        padding-right: is-windowed ? Theme.spacingHorizontalXL : Theme.spacingHorizontalL;
        @children
    }
}

export component ContentDialogInline inherits Rectangle {
    in-out property <bool> is-open: false;
    in property <length> dialog-width: 460px;
    in property <bool> has-footer: false;
    in property <color> footer-background: Theme.colorNeutralBackground1;
    in property <color> footer-border-color: Theme.colorNeutralStroke3;

    overlay := TouchArea {
        z: 1000;
        visible: root.is-open;
        enabled: self.visible;

        Rectangle {
            background: Colors.black.with-alpha(0.32);
            animate background { duration: Theme.durationFast; }
        }
    }
    ContentDialog {
        z: 1001;
        x: (parent.width - self.width) / 2;
        y: Math.max(Theme.spacingVerticalXL, (parent.height - self.height) / 2);
        dialog-width: root.dialog-width;
        has-footer: root.has-footer;
        footer-background: root.footer-background;
        footer-border-color: root.footer-border-color;

        @children
    }
}

export component ContentDialogWindow inherits Window {
    in property <bool> is-open: false;
    in property <length> dialog-width: 460px;
    in property <bool> has-footer: false;
    in property <color> footer-background: Theme.colorNeutralBackground1;
    in property <color> footer-border-color: Theme.colorNeutralStroke3;

    width: root.dialog-width + Theme.spacingHorizontalXL * 2;
    background: Colors.transparent;
    no-frame: true;

    Rectangle {
        background: Colors.transparent;

        dialog := ContentDialog {
            x: Theme.spacingHorizontalXL;
            y: Theme.spacingVerticalXL;
            width: root.dialog-width;
            dialog-width: root.dialog-width;
            has-footer: root.has-footer;
            footer-background: root.footer-background;
            footer-border-color: root.footer-border-color;

            @children
        }
    }
}
