[package]
name = "domain2"
version.workspace = true
edition.workspace = true

[dependencies]
app-contracts2 = { workspace = true }
guinea = { workspace = true, features = ["widgets"] }
guinea-core = { workspace = true }
guinea-macros = { workspace = true }
amethystate = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
cfg-if = { workspace = true }
rkyv = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ogurpchik = { workspace = true }
uniproc-protocol = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
