import { Icons } from "icons.slint";

export struct PageEntry {
    id: int,
    text: string,
    icon: image,
}

export global Dashboard {
    in property <[PageEntry]> pages: [
        { id: 0, text: "Processes", icon: Icons.app },
        { id: 1, text: "Performance", icon: Icons.data-area },
        { id: 2, text: "Disk", icon: Icons.database },
        { id: 3, text: "Statistics", icon: Icons.statistics },
        { id: 4, text: "Startup apps", icon: Icons.dashed-settings },
        { id: 5, text: "Users", icon: Icons.people },
        { id: 6, text: "Services", icon: Icons.puzzle },
    ];

    callback request_page_switch(int);
}
