import {
    Button,
    VerticalBox,
    HorizontalBox,
    StandardTableView,
    ComboBox,
} from "std-widgets.slint";
import { TitleBar } from "title/title-bar.slint";
import { Content } from "content/index.slint";
import { SideBar } from "features/navigation/sidebar.slint";
import { ContextMenuProxy } from "features/processes/context-menu/globals.slint";
import { ResizeHandler } from "utils/resize-area.slint";
import { WslDistro } from "features/environments/globals.slint";

export * from "globals-export.slint";

export component AppWindow inherits Window {

    min-width: 800px;
    min-height: 600px;

    no-frame: true;
    background: transparent;
    default-font-family: "Segoe UI Variable Display";
    always-on-top: false;
    
    callback start_resize(int);
    
    VerticalLayout {
        padding: 0;
        spacing: 0;

        TitleBar { }

        HorizontalLayout {
            SideBar { }

            Content { }
        }
    }

    if (ContextMenuProxy.is-open): TouchArea {
        z: 9999;
        pointer-event(evt) => {
            if (evt.kind == PointerEventKind.down) {
                ContextMenuProxy.is-open = false;
                ContextMenuProxy.close-menu();
            }
        }
    }

    ResizeHandler {
        resize_requested(dir) => {
            root.start_resize(dir);
        }
    }
}
