import { ProcessView } from "process-view.slint";
import {
    ContextMenuProxy,
    MainBodyState,
    Theme,
    Navigation,
} from "globals.slint";
import { LoaderArea } from "loader-area.slint";


export component MainBody inherits Rectangle {
    background: #191919;
    border-top-left-radius: 8px;
    clip: true;

    init => {
        Navigation.request-tab-switch(0);
    }

    content-layer := Rectangle {
        opacity: Navigation.content-visible ? 1 : 0;
        y: Navigation.content-visible ? 0px : 30px;

        animate opacity {
            duration: 150ms;
            easing: ease-in-out;
        }
        animate y {
            duration: 400ms;
            easing: cubic-bezier(0.1, 0.9, 0.2, 1.0);
        }

        Rectangle {
            visible: Navigation.active-tab == 0;

            ProcessView {
                width: 100%;
                height: 100%;
            }
        }

        Rectangle {
            visible: Navigation.active-tab == 1;
            Text {
                text: "Performance Tab";
                color: white;
                font-size: 20px;
                x: 20px;
                y: 20px;
            }
        }

        Rectangle {
            visible: Navigation.active-tab == 2;
            Text {
                text: "Settings / Info";
                color: #aaa;
                x: 20px;
                y: 20px;
            }
        }
    }
}
