[package]
name = "desktop2"
version.workspace = true
edition.workspace = true

[dependencies]
app-contracts2 = { workspace = true }
domain2 = { workspace = true }
guinea = { workspace = true }
guinea-core = { workspace = true }
guinea-macros = { workspace = true }
ui2 = { workspace = true }
guicons = { workspace = true, features = ["windows-reactor"] }
guinea-meta = { workspace = true }
guinea-trace = { workspace = true }
amethystate = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
unic-langid = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
windows-reactor = { workspace = true }

[build-dependencies]
windows-reactor-setup = { workspace = true }
guinea-meta-build = { workspace = true }

[lints]
workspace = true
