import { Theme } from "theme.slint";
import { Icons } from "../../../../shared/icons.slint";

export component NavItem inherits Rectangle {
    in-out property <image> icon;
    in-out property <string> text: "Processes";
    in-out property <bool> active;
    in-out property <bool> has-icon: true;
    in property <bool> colorize: true;
    in property <bool> indicator-visible: false;
    in property <length> indicator-height: Theme.selection_indicator_height;
    in property <length> indicator-offset-y: (self.height - root.indicator-height) / 2;

    callback clicked;

    height: 40px;
    clip: true;
    background: active ? Theme.fill_subtle_secondary : (touch.has-hover ? Theme.fill_subtle_hover : transparent);
    animate background { duration: Theme.primary_animation_time; }
    border-radius: 6px;

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked()
        }
    }

    Rectangle {
        x: 0;
        y: root.indicator-offset-y;
        width: Theme.selection_indicator_width;
        height: root.indicator-height;
        visible: root.indicator-visible;
        background: Theme.accent;
        border-radius: Theme.border_radius_xs;
    }

    HorizontalLayout {
        padding-left: 12px;
        spacing: 12px;

        if (root.has-icon): VerticalLayout {
            alignment: center;
            Image {
                source: root.icon;
                width: 20px;
                height: 20px;
                image-fit: contain;
                animate colorize { duration: Theme.primary_animation_time; }
            }
        }

        Text {
            text: root.text;
            vertical-alignment: center;
            font-size: Theme.font_size_body;
            color: active ? Theme.text_primary : Theme.text_secondary;
            animate color { duration: Theme.primary_animation_time; }
        }
    }
}
