import { Theme } from "theme.slint";
import { Navigation } from "../globals/tabs-navigation.slint";
import { BrowserTabItem } from "components/tab-item.slint";
import { Icons } from "icons.slint";
import { Divider } from "divider.slint";
import { ContextMenu } from "context-menu.slint";
component AvailableContextItem inherits Rectangle {
    in property <string> title;
    in property <string> context-key;
    in property <image> icon;
    callback selected(string);

    height: 32px;
    border-radius: 6px;
    background: area.has-hover ? Theme.colorNeutralBackgroundAlpha3 : transparent;

    area := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.selected(root.context-key);
        }
    }

    HorizontalLayout {
        padding-left: 10px;
        padding-right: 10px;
        spacing: 8px;

        Image {
            source: root.icon;
            width: 16px;
            height: 16px;
            image-fit: contain;
            vertical-alignment: center;
        }

        Text {
            text: root.title;
            vertical-alignment: center;
            color: white;
        }
    }
}

export component TabBar inherits Rectangle {
    y: 0.5px;
    HorizontalLayout {
        alignment: start;
//        padding-left: Theme.spacingHorizontalS;
        for tab[i] in Navigation.tabs: VerticalLayout {
            alignment: end;
            BrowserTabItem {
                title: tab.title;
                icon: tab.icon;
                active: Navigation.active_tab_index == i;
                is-first: i == 0;
                is-closable: tab.is_closable;
                status: tab.status;
                clicked => {
                    Navigation.request_tab_switch(tab.context_key);
                }
                close_clicked => {
                    Navigation.request_tab_close(tab.context_key);
                }
            }
        }

        VerticalLayout {
            alignment: center;
            padding-top: 4px;

            HorizontalLayout {
                padding-left: Theme.spacingHorizontalL;
                spacing: Theme.spacingHorizontalS;

                relative-this := Image {
                    source: Icons.arrow-up-regular;
                    colorize: Navigation.available-contexts.length > 0 ? white : Theme.colorNeutralForegroundDisabled;
                    width: 12px;
                    height: 12px;
                    y: 3px;

                    vertical-alignment: center;
                    transform-rotation: -90deg;
                    transform-origin: { x: 2.5px, y: 5px };
                    add-touch := TouchArea {
                        mouse-cursor: pointer;
                        clicked => {
//                            if (Navigation.available-contexts.length > 0) {
                                popup.show();
//                            }
                        }
                    }
                }
            }
        }
    }

    property <bool> menu-entering;
    menu-enter-timer := Timer {
        interval: 1ms;
        running: false;
        triggered => {
            menu-enter-timer.running = false;
            root.menu-entering = true;
        }
    }

    //    export struct ContextMenuItem {
//        id: string,
//        title: string,
//        icon: image,
//        is-danger: bool,
//        has-separator: bool,
//    }
    popup := ContextMenu {
        items: [{
            id: 0,
            title: "lol",
        }];
        x: relative-this.x + self.width / 4 - relative-this.width;
        y: 40px;
        is-entering: true;

        changed visible => {
            if (!self.visible) {
                root.menu-entering = false;
            }
        }

        action(id) => {
//            root.context-menu-action(id);
        }
    }
}
