
import { ProcessesFeatureGlobal } from "../features/processes/globals.slint";
import { WindowControls } from "controls.slint";
import { Theme } from "theme.slint";
import { Icons } from "icons.slint";

export global WindowClickHandler {
    callback window-clicked();

    window-clicked => {
        ProcessesFeatureGlobal.select_process(-1, -1);
    }
}

export global TitleBarActions {
    callback drag();
    callback close();
    callback minimize();
    callback maximize();
}

export component TitleBar {

    height: Theme.title_bar_height;
    unfocus := TouchArea {
        pointer-event(evt) => {
            if (evt.kind == PointerEventKind.down) {
                WindowClickHandler.window-clicked();
            }
        }
    }

    Rectangle {
        height: 48px;

        TouchArea {
            moved => {
                TitleBarActions.drag();
            }
        }

        HorizontalLayout {
            spacing: Theme.spacingHorizontalL;
            padding-left: Theme.spacingHorizontalL;

            VerticalLayout {
                alignment: center;
                Image {
                    source: Icons.uniproc-logo;
                    width: 24px;
                    height: 16px;
                    image-fit: contain;
                }
            }

            Text {
                vertical-alignment: center;
                color: white;
                font-size: 12px;
                text: "Uniproc";
            }

            WindowControls {
                minimize => {
                    TitleBarActions.minimize();
                }
                maximize => {
                    TitleBarActions.maximize();
                }
                close => {
                    TitleBarActions.close();
                }
            }
        }
    }
}
