import { Theme } from "theme.slint";
import { ProcessView } from "../features/processes/process-view.slint";
import {
    Navigation,
} from "../features/navigation/globals/tabs-navigation.slint";


export component Content inherits Rectangle {
    background: Theme.background;
    border-top-left-radius: Theme.border_radius_m;
    clip: true;

    init => {
        Navigation.request-tab-switch(0);
    }

    content-layer := Rectangle {
        opacity: Navigation.content-visible ? 1 : 0;
        y: Navigation.content-visible ? 0px : 30px;

        animate opacity {
            duration: 150ms;
            easing: ease-in-out;
        }
        animate y {
            duration: 400ms;
            easing: cubic-bezier(0.1, 0.9, 0.2, 1.0);
        }

        Rectangle {
            visible: Navigation.active_tab_index == 0;

            ProcessView {
                width: 100%;
                height: 100%;
            }
        }

        Rectangle {
            visible: Navigation.active_tab_index == 1;
            Text {
                text: "Performance Tab";
                color: white;
                font-size: 20px;
                x: 20px;
                y: 20px;
            }
        }

        Rectangle {
            visible: Navigation.active_tab_index == 2;
            Text {
                text: "Settings / Info";
                color: #aaa;
                x: 20px;
                y: 20px;
            }
        }

        Rectangle {
            visible: Navigation.active_tab_index == 3;
            Text {
                text: "Settings / Info";
                color: #aaa;
                x: 20px;
                y: 20px;
            }
        }

        Rectangle {
            visible: Navigation.active_tab_index == 4;
            Text {
                text: "Settings / Info";
                color: #aaa;
                x: 20px;
                y: 20px;
            }
        }

        Rectangle {
            visible: Navigation.active_tab_index == 5;
            Text {
                text: "Settings / Info";
                color: #aaa;
                x: 20px;
                y: 20px;
            }
        }

        Rectangle {
            visible: Navigation.active_tab_index == 6;
            Text {
                text: "Settings / Info";
                color: #aaa;
                x: 20px;
                y: 20px;
            }
        }
    }
}
