import {
    ServiceViewHeader,
    ServiceViewBody,
    ServicePropertiesInlineOverlay,
} from "../../../../features/services/service-view.slint";

export global ServicesPageSpec {
    out property <string> layout: "with-sidebar";
}

export component ServicesPageHeader {
    ServiceViewHeader { }
}

export component ServicesPageBody {
    ServiceViewBody { }
}

export component ServicesPageOverlay {
    ServicePropertiesInlineOverlay { }
}
