import { Theme } from "theme.slint";
import { PageStatus } from "../../../../content/globals.slint";
import { Button } from "button/index.slint";
import { Icons } from "icons.slint";

export component BrowserTabItem inherits Rectangle {
    in-out property <string> title;
    in-out property <bool> active;
    in property <bool> is-first;
    in property <image> icon;
    in property <bool> is-closable: false;
    in property <PageStatus> status: PageStatus.inactive;
    callback clicked;
    callback close_clicked;

    private property <bool> is-hovered: touch.has-hover;

    border-radius: Theme.borderRadiusLarge;
    height: 32px;
    width: 150px;

    animate background { duration: Theme.durationFaster; }

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => { root.clicked() }
    }

    Path {
        x: -Theme.borderRadiusLarge;
        y: 0;
        width: root.width + 2 * Theme.borderRadiusLarge;
        height: root.height;
        fill: active
            ? Theme.colorNeutralBackgroundAlpha
            : is-hovered
                ? Theme.colorNeutralBackgroundAlpha3
                : transparent;
        stroke-width: 1px;

        animate stroke { duration: Theme.durationFaster; }

        stroke: active
            ? Theme.colorNeutralStrokeAlpha
            : transparent;

        private property <float> r: Theme.borderRadiusLarge / 1px;
        private property <float> w: root.width / 1px;
        private property <float> h: root.height / 1px;

        MoveTo { x: 0;         y: h;     }
        ArcTo  { radius-x: r; radius-y: r; x: r;     y: h - r; sweep: false; }

        LineTo { x: r;         y: r;     }
        ArcTo  { radius-x: r; radius-y: r; x: r * 2; y: 0;     sweep: true;  }

        LineTo { x: w;         y: 0;     }
        ArcTo  { radius-x: r; radius-y: r; x: w + r; y: r;     sweep: true;  }

        LineTo { x: w + r;     y: h - r; }
        ArcTo  { radius-x: r; radius-y: r; x: w + r * 2; y: h; sweep: false;  }
    }
    VerticalLayout {
        alignment: center;

        HorizontalLayout {
            padding-left: Theme.spacingHorizontalMNudge;
            padding-right: Theme.spacingHorizontalSNudge;
            spacing: 8px;

            if (root.icon.width > 0): VerticalLayout {
                alignment: center;
                Image {
                    source: root.icon;
                    width: 16px;
                    height: 16px;
                    image-fit: contain;
                    vertical-alignment: center;
                }
            }

            Text {
                text: root.title;
                overflow: elide;
                font-weight: active ? 700 : 400;
                vertical-alignment: center;
            }
            Rectangle { horizontal-stretch: 1; }
            if (root.is-closable): Button {
                icon: Icons.dismiss;
                icon-size: 14px;
                prop-padding-left: 4px;
                prop-padding-right: 4px;
                height: 24px;
                is-transparent: true;
                clicked => {
                    root.close_clicked();
                }
            }
        }
    }
}
