
export enum PageStatus {
    inactive,
    loading,
    ready,
    error
}

export struct PageData {
    path: string,
    route_segment: string,
    text: string,
    icon: image,
    status: PageStatus,
    error_msg: string,
}

export struct TabData {
    id: int,
    context_key: string,
    title: string,
    icon: image,
    pages: [PageData],
    status: PageStatus,
    error_msg: string,
    is_closable: bool,
}

export struct AvailableContextData {
    context_key: string,
    title: string,
    icon: image,
    status: PageStatus,
}

