import { BuiltinDashboard } from "../builtin/dashboard.slint";
import { TabData } from "../content/globals.slint";
import { Theme } from "theme.slint";
import { Tabs } from "../features/tabs/globals.slint";
export component ContentContainer inherits Rectangle {
    clip: true;
    background: Theme.colorNeutralBackgroundAlpha;
    private property <TabData> active_tab: Tabs.tabs[Tabs.active_tab_index];

    if (Tabs.tabs.length > 0): BuiltinDashboard { }
    if (Tabs.tabs.length == 0): Rectangle { }
}
