import { Theme } from "theme.slint";
import { ResizeHandle } from "resize-handle.slint";
export component ResizableHeaderCell inherits Rectangle {
    in property <length> column-width;
    in property <length> prop-min-width: 40px;
    in property <string> column-id;
    callback resized(string, float);

    width: column-width;
    HorizontalLayout {
        padding-left: 6px;
        padding-right: 6px;
        @children
    }

    ResizeHandle {
        x: parent.width - (self.width / 2);

        resized(delta) => {
            let new-w = root.column-width + delta;
            if (new-w >= root.prop-min-width) {
                root.resized(root.column-id, new-w / 1px);
            }
        }
    }
}
