import {
    TableColDef,
    TableColWidth,
    TableColMetadata,
    TableCellData,
} from "../../components/table/index.slint";

export struct ServiceEntry {
    name: string,
    display-name: string,
    pid: int,
    status: string,
    group: string,
    description: string,
    cells: [TableCellData],
}

export global ServicesFeatureGlobal {

    in property <[TableColDef]> column-defs:[
        { id: "name", label: "Name" },
        { id: "pid", label: "PID" },
        { id: "status", label: "Status" },
        { id: "group", label: "Group" },
        { id: "description", label: "Description" },
    ];

    in-out property <[TableColMetadata]> column-metadatas:[
        { is-text: true },
        { is-text: true },
        { is-text: true },
        { is-text: true },
        { is-text: true }
    ];

    in-out property <[TableColWidth]> column-widths:[
        { id: "name", width-px: 150 },
        { id: "pid", width-px: 80 },
        { id: "status", width-px: 100 },
        { id: "group", width-px: 120 },
        { id: "description", width-px: 100 },
    ];

    in property <[ServiceEntry]> service-rows:[];
    in property <string> selected-name: "AudioEndpointBuilder";
    in property <string> selected-display-name: "Windows Audio Endpoint Builder";
    in property <int> selected-pid: -1;
    in property <string> selected-status: "Running";
    in property <string> selected-group: "AudioGroup";
    in property <string> selected-description: "Manages audio devices for the Windows audio service.";
    in property <string> current-sort;
    in property <bool> current-sort-descending;
    in property <int> total-services-count;
    in property <bool> is-loading;

    in property <bool> start-button-active: false;
    in property <bool> stop-button-active: true;
    in property <bool> restart-button-active: true;
    in-out property <bool> properties-inline-open: false;

    callback sort-by(string);
    callback select-service(string, int);
    callback rows-viewport-changed(int, int);
    callback column-resized(string, float);
    callback service-action(string, string);
    callback open-system-services();
    callback open-properties-window();
}
