import { TableColDef, TableColWidth, TableColMetadata } from "table-view.slint";

export struct ProcessField {
    id: string,
    text: string,
    numeric: float,
    threshold: float,
}

export struct ProcessEntry {
    pid: int,
    name: string,
    icon: image,
    depth: int,
    has-children: bool,
    is-expanded: bool,
    is-dead: bool,
    fields: [ProcessField],
}

export struct ProcessGroup {
    parent: ProcessEntry,
    children: [ProcessEntry],
}

export global ProcessesFeatureGlobal {
    in property <[TableColDef]> column-defs: [
        {
            id: "name",
            label: "Name",
            is-text: true,
        },
        {
            id: "cpu",
            label: "CPU",
            stat-text: "46%",
            stat-numeric: 46.0,
            threshold: 50.0,
            stat-detail: "1,4 GHz",
            show-indicator: true
        },
        {
            id: "memory",
            label: "Memory",
            stat-text: "71%",
            stat-numeric: 71.0,
            threshold: 80.0,
            stat-detail: "32,5/64GB",
            show-indicator: true
        },
        {
            id: "disk",
            label: "Disk",
            stat-text: "125 b/s",
            stat-numeric: 0.0,
            threshold: 70.0,
            show-indicator: false
        },
        {
            id: "net",
            label: "Network",
            stat-text: "55 kb/s",
            stat-numeric: 5.0,
            threshold: 70.0,
            show-indicator: false
        },
    ];
    in-out property <[TableColMetadata]> column-metadatas: [
        { is-text: true },
        { is-metric: true },
        { is-metric: true },
        { is-metric: true },
        { is-metric: true }
    ];
    in-out property <[TableColWidth]> column-widths: [
        { id: "name", width-px: 190 },
        { id: "cpu", width-px: 85 },
        { id: "memory", width-px: 120 },
        { id: "disk", width-px: 70 },
        { id: "net", width-px: 70 },
    ];
    callback column-resized(string, float);

    in property <[ProcessGroup]> process-groups: [];
    in property <[ProcessEntry]> process-rows: [
        {
            pid: 1,
            name: "Taskmgr sucks",
            is-dead: false,
            is-expanded: true,
            depth: 0,
            has-children: true,
            fields: [
                { id: "cpu", text: "12.5%", numeric: 12.5, threshold: 50.0 },
                { id: "memory", text: "1.4 GiB", numeric: 1.4, threshold: 1.0 },
                { id: "disk", text: "500 KiB/s", numeric: 75.0, threshold: 70.0 },
                { id: "net", text: "100 KB/s", numeric: 100.0, threshold: 70.0 },
            ]
        },
        {
            pid: 2,
            name: "Taskmgr sucks",
            is-dead: false,
            is-expanded: false,
            depth: 1,
            has-children: false,
            fields: [
                { id: "cpu", text: "4.2%", numeric: 4.2, threshold: 50.0 },
                { id: "memory", text: "300 MiB", numeric: 0.3, threshold: 1.0 },
                { id: "disk", text: "0 KiB/s", numeric: 0.0, threshold: 70.0 },
                { id: "net", text: "20 KB/s", numeric: 2.0, threshold: 70.0 },
            ]
        },
    ];
    in-out property <int> selected-pid: -1;
    in property <string> selected-name;
    in property <string> current-sort;
    in property <bool> current-sort-descending;
    in property <int> total-processes-count;
    callback sort-by(string);
    callback toggle-expand-group(string);
    callback select-process(int, int);
    callback rows-viewport-changed(int, int);
    callback terminate();
}
