[package]
name = "app-contracts2"
version.workspace = true
edition.workspace = true

[dependencies]
guinea = { workspace = true }
guinea-core = { workspace = true }
guinea-macros = { workspace = true }
inventory = { workspace = true }
anyhow = { workspace = true }
fluent-templates = { workspace = true }
fluent-bundle = { workspace = true }
unic-langid = { workspace = true }
cfg-if = { workspace = true }
rkyv = { workspace = true }
uuid = { workspace = true }
ogurpchik = { workspace = true }
uniproc-protocol = { workspace = true }
guicons = { workspace = true }
amethystate = { workspace = true }
serde = { workspace = true }

[build-dependencies]
guinea-codegen = { workspace = true }
guicons-build = { workspace = true }

[lints]
workspace = true
