import {
    Button,
    VerticalBox,
    HorizontalBox,
    StandardTableView,
    ComboBox,
} from "std-widgets.slint";
import { TitleBar } from "title/title-bar.slint";
import { ContentContainer } from "content/index.slint";
import { SideBar } from "features/navigation/sidebar/index.slint";
import { ContextMenuProxy } from "features/processes/context-menu/globals.slint";
import { ResizeHandler } from "components/resize-area.slint";
import { WslDistro } from "features/environments/globals.slint";
import { WindowSize, WindowAdapter } from "window-adapter.slint";
export * from "globals-export.slint";

export component AppWindow inherits Window {

    min-width: 400px;
    min-height: 300px;

    no-frame: true;
    background: transparent;
    default-font-family: "Segoe UI Variable Display";
    always-on-top: false;
    
    callback start_resize(int);

    changed width => {
        WindowAdapter.window-width = root.width;
        if (root.width < 600px) {
            if (WindowAdapter.size != WindowSize.sm) {
                WindowAdapter.size = WindowSize.sm;
                WindowAdapter.size-changed(WindowSize.sm);
            }
        } else if (root.width < 1024px) {
            if (WindowAdapter.size != WindowSize.md) {
                WindowAdapter.size = WindowSize.md;
                WindowAdapter.size-changed(WindowSize.md);
            }
        } else {
            if (WindowAdapter.size != WindowSize.lg) {
                WindowAdapter.size = WindowSize.lg;
                WindowAdapter.size-changed(WindowSize.lg);
            }
        }
    }

    VerticalLayout {
        padding: 0;
        spacing: 0;

        TitleBar { }

        HorizontalLayout {
            ContentContainer { }
        }
    }

    if (ContextMenuProxy.is-open): TouchArea {
        z: 9999;
        pointer-event(evt) => {
            if (evt.kind == PointerEventKind.down) {
                ContextMenuProxy.is-open = false;
                ContextMenuProxy.close-menu();
            }
        }
    }

    ResizeHandler {
        resize_requested(dir) => {
            root.start_resize(dir);
        }
    }
}
