import { MainBodyState } from "content/globals.slint";

import {
    EnvironmentsFeatureGlobal,
    EnvsLoading,
    WslDistro,
} from "features/environments/globals.slint";

import {
    Dashboard,
    PageEntry,
} from "features/navigation/globals/dashboard.slint";

import {
    Navigation,
    TabData,
} from "features/navigation/globals/tabs-navigation.slint";

import {
    ProcessEntry,
    ProcessesFeatureGlobal,
    ProcessGroup,
    FieldDef,
    ProcessField,
} from "features/processes/globals.slint";

import {
    ContextMenuProxy,
} from "features/processes/context-menu/globals.slint";
import {
    ProcessContextMenu,
} from "features/processes/context-menu/index.slint";

import { TitleBarActions, WindowClickHandler } from "title/title-bar.slint";

import {
    RunEnv,
    RunTaskDialog,
    RunTaskProxy,
} from "features/processes/run-task-dialog.slint";


import { Theme } from "theme.slint";

import { L10n } from "localization.slint";

export { 
    MainBodyState, EnvironmentsFeatureGlobal, EnvsLoading,
    WslDistro, Navigation, TabData, 
    ProcessEntry, ProcessesFeatureGlobal, ProcessGroup,
    ContextMenuProxy, Theme, L10n, ProcessContextMenu,
    PageEntry, TitleBarActions, WindowClickHandler,
    RunEnv, RunTaskDialog, RunTaskProxy, Dashboard
}
