[package]
name = "desktop"
version.workspace = true
edition.workspace = true

[dependencies]
app-contracts = { workspace = true }
domain = { workspace = true }
guinea = { workspace = true }
guinea-core = { workspace = true }
guinea-macros = { workspace = true }
ui = { workspace = true }
guicons = { workspace = true, features = ["windows-reactor"] }
guinea-meta = { workspace = true }
guinea-trace = { workspace = true }
amethystate = { workspace = true }
guinea-plugin-store = { workspace = true }
guinea-plugin-l10n = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
unic-langid = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
windows-collections = { workspace = true }
windows-core = { workspace = true }
windows-reference = { workspace = true }
windows-reactor = { workspace = true }

[build-dependencies]
windows-reactor-setup = { workspace = true }
guinea-meta-build = { workspace = true }

[lints]
workspace = true
