
import { Theme } from "theme.slint";
import { Environments } from "../environments/distro.slint";
import { Navigation } from "globals/tabs-navigation.slint";
import { Dashboard } from "globals/dashboard.slint";
import { SelectionIndicator } from "../../components/selection-indicator.slint";
import { WindowClickHandler } from "../../title/title-bar.slint";

component SideBarItem inherits Rectangle {
    in-out property <image> icon;
    in-out property <string> text: "Processes";
    in-out property <bool> active;
    in-out property <bool> has-icon: true;
    in property <bool> colorize: true;

    callback clicked;

    height: 40px;
    background: active ? Theme.fill_subtle_secondary : (touch.has-hover ? Theme.fill_subtle_hover : transparent);
    animate background { duration: 100ms; }
    border-radius: 6px;

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            root.clicked()
        }
    }

    SelectionIndicator {
        is-active: root.active;

        y: (parent.height - self.height) / 2;
    }

    HorizontalLayout {
        padding-left: 12px;
        spacing: 12px;

        if (root.has-icon): VerticalLayout {
            alignment: center;
            Image {
                source: root.icon;
                width: 20px;
                height: 20px;
                image-fit: contain;
                animate colorize { duration: Theme.primary_animation_time; }
            }
        }

        Text {
            text: root.text;
            vertical-alignment: center;
            font-size: Theme.font_size_body;
            color: active ? Theme.text_primary : Theme.text_secondary;

            animate color { duration: Theme.primary_animation_time; }
        }
    }
}

export component SideBar inherits Rectangle {

    accessible-role: AccessibleRole.button;
    width: 260px;
    unfocus := TouchArea {
        pointer-event(evt) => {
            if (evt.kind == PointerEventKind.down) {
                WindowClickHandler.window-clicked();
            }
        }
    }

    VerticalLayout {
        padding: 6px;
        spacing: 4px;
        alignment: start;

        Environments { }

        Rectangle {
            height: 16px;
        }

        for page in Dashboard.pages: SideBarItem {
            icon: page.icon;
            text: page.text;
            active: Dashboard.active_page == page.id;
            colorize: false;
            clicked => {
                Navigation.request_tab_switch(page.id);
            }
        }
    }
}
