

import { Theme } from "theme.slint";
import { Navigation } from "globals/tabs-navigation.slint";
component BrowserTabItem inherits Rectangle {
    in-out property <string> title;
    in-out property <bool> active;
    callback clicked;
    callback close_clicked;

    width: 180px;
    height: 36px;
    background: active ? Theme.accent : transparent;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px;

    TouchArea {
        clicked => {
            root.clicked()
        }
    }

    HorizontalLayout {
        padding-left: 12px;
        padding-right: 8px;
        spacing: 8px;
        alignment: center;

        Text {
            text: root.title;
            color: active ? white : rgba(255, 255, 255, 0.6);
            font-size: 13px;
            overflow: elide;
        }

        if active: Rectangle {
            width: 16px;
            height: 16px;
            border-radius: 4px;
            Text {
                text: "×";
                font-size: 16px;
                color: white;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            TouchArea {
                clicked => {
                    root.close_clicked()
                }
            }
        }
    }

    if !active: Rectangle {
        y: parent.height - 1px;
        height: 1px;
        background: rgba(255, 255, 255, 0.1);
    }
}

export component TabBar inherits Rectangle {
    height: 40px;
    background: #191919;

    HorizontalLayout {
        alignment: start;
        padding-left: 10px;
        padding-top: 4px;

        for tab[i] in Navigation.tabs: BrowserTabItem {
            title: tab.title;
            active: Navigation.active_tab_index == i;
            clicked => {
                Navigation.request_tab_switch(i);
            }
            close_clicked => {
                Navigation.request_tab_close(i);
            }
        }

        Rectangle {
            width: 30px;
            Text {
                text: "+";
                color: white;
                font-size: 20px;
            }

            TouchArea {
                clicked => {
                    Navigation.request_tab_add();
                }
            }
        }
    }
}
